// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh8yEQQPHv14UM56eVGst02RlmBIGp7EE',
    appId: '1:458527651729:web:73773d658698abe4b24c30',
    messagingSenderId: '458527651729',
    projectId: 'ingrediapp-aa9c1',
    authDomain: 'ingrediapp-aa9c1.firebaseapp.com',
    storageBucket: 'ingrediapp-aa9c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_0NUWGPz87YrOPKNOLIrvqnBekL_r6Vo',
    appId: '1:458527651729:android:cd53558146ba4f7bb24c30',
    messagingSenderId: '458527651729',
    projectId: 'ingrediapp-aa9c1',
    storageBucket: 'ingrediapp-aa9c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcH5MNkB2iY1lNyXaT10nyv3xEOSEfjK4',
    appId: '1:458527651729:ios:68be44a179b5e326b24c30',
    messagingSenderId: '458527651729',
    projectId: 'ingrediapp-aa9c1',
    storageBucket: 'ingrediapp-aa9c1.firebasestorage.app',
    iosBundleId: 'com.example.ingrediapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcH5MNkB2iY1lNyXaT10nyv3xEOSEfjK4',
    appId: '1:458527651729:ios:68be44a179b5e326b24c30',
    messagingSenderId: '458527651729',
    projectId: 'ingrediapp-aa9c1',
    storageBucket: 'ingrediapp-aa9c1.firebasestorage.app',
    iosBundleId: 'com.example.ingrediapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh8yEQQPHv14UM56eVGst02RlmBIGp7EE',
    appId: '1:458527651729:web:9cd97c5e1b46e0d7b24c30',
    messagingSenderId: '458527651729',
    projectId: 'ingrediapp-aa9c1',
    authDomain: 'ingrediapp-aa9c1.firebaseapp.com',
    storageBucket: 'ingrediapp-aa9c1.firebasestorage.app',
  );
}
